### ISSUE TITLE
Special coloring for uniforms and varyings

### ISSUE THREAD

**Issue by MattijsKneppers** [Darkyenus/glsl4idea#119]
It would be a great addition if uniforms and varyings would have different colors than inline variables, just like class members in typescript files have a different color than inline variables and function arguments (see attached image)

This way, using a naming convention for uniforms and varyings like uBla or vBla would no longer be necessary.

![coloring example](https://cloud.githubusercontent.com/assets/299714/16981841/e2cd2e10-4e6c-11e6-8c76-33f6092383f7.png)

**Comment by Darkyenus** [comment]
Good idea! Added in [latest commit](https://github.com/Darkyenus/glsl4idea/commit/3e248a892f4c3dd418defc5e34a5822114e3bb00).

Since there is not enough changes for a full release yet, you can compile yourself or use attached jar.

[GLSL4Idea.jar.zip](https://github.com/Darkyenus/glsl4idea/files/376584/GLSL4Idea.jar.zip)

**Comment by MattijsKneppers** [comment]
Thanks for getting on it so quickly!

I tried using the new feature but as far as I can see it doesn't work (see screenshot), could I be missing something?

![coloring](https://cloud.githubusercontent.com/assets/299714/17096837/98494124-525b-11e6-8a5f-89154cde6fd7.png)

**Comment by Darkyenus** [comment]
Yeah, it does not work in preview because it needs type info which is not available there - internally it is similar to those "quick fix" popups.

Attributes added, try this build: [GLSL4Idea.jar.zip](https://github.com/Darkyenus/glsl4idea/files/385560/GLSL4Idea.jar.zip) (or build it yourself from source)

**Comment by MattijsKneppers** [comment]
Awesome!!
