### ISSUE TITLE
Return type vec marked as void caused Invalid types error

### ISSUE THREAD

**Issue by guusie500** [Darkyenus/glsl4idea#131]
The following code gives a red line below 'return(result)' saying 'Incompatibel types. Required: void, found vec4'. The shader does compile and run in my program. Writing doen 'return result' does not change the behaviour.

vec4 cone() {
    vec4 result = vec4(0.0, 0.0, 0.0, 1.0);
    return(result);
}

**Comment by Darkyenus** [comment]
I would bet that when you were editing, you first wrote `void cone() {` and then changed it to `vec4`.

This problem sometimes happens when editing, because the type analyzer is currently slightly broken and does not recognize when the type changes. As a workaround before it gets fixed, you can Ctrl+A to select all, then Ctrl-X and Ctrl-V to force reparsing of the file.

I'd really like to fix these, along with more robust refactoring, but the documentation of these parts of the plugin API is poor and finding information about it sadly takes more time than I currently have.
