### ISSUE TITLE
Cannot enable GLSL language injection in C++ in CLion

### ISSUE THREAD

**Issue by singalen** [Darkyenus/glsl4idea#155]
I have C++ file with shader code in a string literal.
Adding `// language=GLSL` before the literal doesn't make it an injected GLSL.
There are no GLSL injections in Preferences - Editor - Language injections, and GLSL is not available as a type when I try to create a new one.
Is there anything I'm missing?

CLion 2020.2
Build #CL-202.6397.78, built on July 23, 2020
Licensed to Victor Sergienko
Subscription is active until April 22, 2021
Runtime version: 11.0.7+10-b944.20 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 6179M
Cores: 8
Registry: run.processes.with.pty=TRUE, ide.settings.move.mouse.on.default.button=true
Non-Bundled Plugins: GLSL, name.kropp.intellij.makefile, org.jetbrains.plugins.rest, org.toml.lang, org.rust.lang, some.awesome

**Comment by Darkyenus** [comment]
I suspect that this isn't implemented in CLion for C++ yet: [CPP-6790](https://youtrack.jetbrains.com/issue/CPP-6790), [CPP-12647](https://youtrack.jetbrains.com/issue/CPP-12647). Also, it does not work for any other languages I have tried to inject this way.

So you will probably have to wait for this to be implemented by Jetbrains.

I'm closing this, because I don't think that I can fix this, but feel free to reopen if you think that this is indeed a bug (or a missing functionality) in this plugin.
