### ISSUE TITLE
Syntax highlighting isn't using editor color scheme

### ISSUE THREAD

**Issue by Kerndog73** [Darkyenus/glsl4idea#158]
This plugin seems to be using a fixed set of colors instead of responding to the editor color scheme that's set. Changing the color scheme doesn't have any effect on the colors chosen by this plugin.

![Screen Shot 2021-06-08 at 16 42 06](https://user-images.githubusercontent.com/10371177/121140521-15f66780-c879-11eb-899f-50be8ce3f249.png)

I would expect `out` and `uniform` to be pink and perhaps `vec4` and `void` could be yellow (although `int` and `void` are pink as well in Java). It would be really nice if this plugin would use the editor color scheme.

**Comment by Darkyenus** [comment]
The plugin uses the standard IntelliJ color configuration mechanism. If you want the colors of particular elements in different languages to match, set the color in Language Defaults and inherit that color in GLSL, Java and other languages.

For example:
![image](https://user-images.githubusercontent.com/5280068/121197986-0fb0bd00-c872-11eb-9aef-5f4b52e1cbe7.png)

If that does not work and you believe that it is due to a bug, please reopen the issue and send a screenshots of relevant settings for GLSL color, Language Defaults and Java/other language, for the same element.
