### ISSUE TITLE
1.20 Broke ability to set .vs .gs .fs as associated file types

### ISSUE THREAD

**Issue by VaderY** [Darkyenus/glsl4idea#161]
1.20 Broke ability to set .vs .gs .fs as associated file types.
After assigning .vs .gs .fs it work perfectly until the IDE is not restarted. After a restart these association are deleted.
Other random test file extensions are working perfectly
Downgraded back to 1.19 solved the issue temporarily

**Comment by Darkyenus** [comment]
Thank you for the report. I don't yet see why would this happen, but I'll look into it as soon as I have some spare time.

**Comment by Firestar99** [comment]
It seems like on restarts it specifically only removes any associated file types which are NOT default but also does NOT add the default ones again.

Example: You can remove all default file associations, save, then add the default "*.glsl" manually and that one will stay after a restart.

**Comment by Darkyenus** [comment]
This was a bug in Intellij: https://youtrack.jetbrains.com/issue/IDEA-274889 . Reverting the plugin version worked probably because the older version used old and deprecated way to handle extensions, which may not have been affected by the same bug.

**Comment by VaderY** [comment]
It looks like the problem still exits (with latest CLion and 1.21)
But the linked IDEA issue has a better workaround that works with the newer versions of the plugin too:
Using *?.vs *?.gs *?.fs instead of *.vs *.gs *.fs

**Comment by Darkyenus** [comment]
I have no idea what could cause it then, I'm pretty sure it is still an IDE issue, because this plugin does very little with file extensions and what it does is 1:1 from the official plugin dev guide, so there is not many places where a bug could hide. And I couldn't reproduce the issue on my end, though I haven't tested in CLion. Maybe CLion updates are just lagging with the IntelliJ platform version and didn't get the fix yet?

**Comment by VaderY** [comment]
Possible, but I think CLion should be on par with other IDEAs.
In any case this smells like an IDEA/Clion bug, and the *?.vs *?.gs *?.fs workaround works perfectly
