### ISSUE TITLE
How to turn off error checking?

### ISSUE THREAD

**Issue by samhains** [Darkyenus/glsl4idea#169]
The error checking for this never seems to work properly, its unable to tell that I am defining other variables and funcitons in other GLSL files that are being put together by my javascript.

SO - I would love to just turn it off? Is there any way to get the syntax highling but not the error checking?

**Comment by Darkyenus** [comment]
Have you tried this https://www.jetbrains.com/help/idea/disabling-and-enabling-inspections.html#change-highlighting-level-for-file ?

**Comment by samhains** [comment]
Yes, I manually disable the error checking for each file using this. But it is tedious to do for every file, and if you switch GitHub branch, it comes back on. I’d love a way to turn off error checking for all glsl files.


--
Sam Hains
www.samhains.com

**Comment by Darkyenus** [comment]
What kinds of errors are you encountering? If you have code that is valid GLSL by one of the specifications, it should be fixed. If your code is syntactically invalid GLSL (some sort of flavour), it could still be added, if it is common or non-intrusive.

If your problem is with "inspections", there is a system that would allow users to disable them, but it would require rewriting all of them, which is a time consuming process.

Feel free to reopen with your reply.
