### ISSUE TITLE
The plugin is not yet available on https://plugins.jetbrains.com/

### ISSUE THREAD

**Issue by agatti** [Darkyenus/glsl4idea#31]
Are there any plans to upload the plugin to JetBrains' repository?  Given that you got the official blessing from the original authors to carry over development I think the next logical step would be to upload an updated version.  Not even JetBrains employees are aware of this version it seems, according to https://youtrack.jetbrains.com/issue/CPP-1536 - and there is definitely the request for such a thing, now that it works under CLion too.  Now that more GLES functionalities are covered, I know for sure that I wouldn't mind having this available on Android Studio too :)

**Comment by Darkyenus** [comment]
I have contacted original authors about getting access to the existing plugin in repository, so I can upload new version.

**Comment by yngvedh** [comment]
I am one of the original authors and I'm sorry about this mess.

The thing is, we got help from Jetbrains to publish the plugin. So much so that they managed the whole plugin in the repository. As a result, we don't even have access.

I requested access by my contact in JetBrains when I was contacted by Darkyenus. But unfortunately, by then, he had left the company. He was nice enough to forward my request to someone inside JetBrains, but I never heard back. I'll try to contact them again to see if I can get this sorted out.

**Comment by Darkyenus** [comment]
Thanks @yngvedh !
In the worst case I can just upload it as a new plugin, but continuing the old one would be far nicer.

**Comment by agatti** [comment]
I've posted on the CLion bug report I mentioned in the issue text, pointing people here.

If pinging folks via email doesn't seem to work, I suspect letting any of their platform evangelists know would be enough, I think.

**Comment by Darkyenus** [comment]
Thanks to @yngvedh I could upload the new version to the [repo](http://plugins.jetbrains.com/plugin/6993). Unless anybody objects, following releases will be uploaded only there.

**Comment by AbigailBuccaneer** [comment]
As a developer I find it useful to have the releases available from GitHub - though that's more from the point of view of seeing what the latest release is compared to master etc., rather than getting the plugin itself from here. Are you intending to still use releases and just not upload the `.jar` for each release, or to entirely drop using the GitHub releases feature?

**Comment by Darkyenus** [comment]
I wanted to drop it entirely, but this is a fair point. Creating a release tags current head which will probably help in the future. So I'll probably still do github releases, but uploading plugin twice is pointless, since it can be downloaded directly from jetbrains repository. That way changenotes stay only in plugin.xml where most people will see them.

**Comment by jepebe** [comment]
Great work getting the plugin updated and published again. :+1:
